### ISSUE TITLE
Meta-data issues with http-dispatch-0.6.1.0 (and others)

### ISSUE THREAD

**Issue by hvr** [owainlewis/http-dispatch#3]
I noticed your recent package upload to Hackage as it was flagged by the matrix buildbot due to  packaging meta-data issues:

 - The `description` ("Please see README.md") is not proper description for your package (and Hackage will show a link to the README at the end of the description *if* the README exists; therefore that phrase is redundant), and hence this will cause poor experience for users (NB: your package won't be properly indexed by Hackage's package search feature and thus hurt its discoverability). See also [this posting](https://mail.haskell.org/pipermail/haskell-cafe/2016-November/125541.html) for more details.

 - The build-dependencies have inaccurate versions bounds. Please be aware that accurate version bounds are mandated by the [PVP](http://pvp.haskell.org/), and adherence to the PVP is expected as part of the Hackage guidelines.  This has various knock off consequences, such as Hackage not being able to generate Haddock documentation for your package, as well generally resulting in a poor experience for users since they'll run into the same compilation errors. Specifically, I've noticed the following compile error on all releases going back to `http-dispatch-0.2.0.0`:

```
Configuring component lib from http-dispatch-0.6.1.0
Preprocessing library http-dispatch-0.6.1.0...
[1 of 5] Compiling Network.HTTP.Dispatch.Types ( src/Network/HTTP/Dispatch/Types.hs, /tmp/matrix-worker/1479552650/dist-newstyle/build/x86_64-linux/ghc-8.0.1/http-dispatch-0.6.1.0/build/Network/HTTP/Dispatch/Types.o )
[2 of 5] Compiling Network.HTTP.Dispatch.Headers ( src/Network/HTTP/Dispatch/Headers.hs, /tmp/matrix-worker/1479552650/dist-newstyle/build/x86_64-linux/ghc-8.0.1/http-dispatch-0.6.1.0/build/Network/HTTP/Dispatch/Headers.o )
[3 of 5] Compiling Network.HTTP.Dispatch.Internal.Request ( src/Network/HTTP/Dispatch/Internal/Request.hs, /tmp/matrix-worker/1479552650/dist-newstyle/build/x86_64-linux/ghc-8.0.1/http-dispatch-0.6.1.0/build/Network/HTTP/Dispatch/Internal/Request.o )

src/Network/HTTP/Dispatch/Internal/Request.hs:41:17: error:
    Not in scope: ‘checkStatus’
```

**Comment by owainlewis** [comment]
Thanks. I will try and fix those issues.

**Comment by hvr** [comment]
@owainlewis I just noticed http-dispatch-0.6.2.0; did you really intend to pin-down the dependencies to single versions with

```
  , http-client == 0.5.4
  , http-client-tls == 0.3.3
  , http-types == 0.9.1
```

?

Didn't you rather intend [PVP](http://pvp.haskell.org)-style ranges as in

```
  , http-client >= 0.5.4 && < 0.6
  , http-client-tls >= 0.3.3 && < 0.4
  , http-types >= 0.9.1 && < 0.10
```

?

**Comment by owainlewis** [comment]
Yes bounded ranges probably make more sense. Just wanted to get it up to scratch to start with. Thanks for the tips 👍
